name: base
channels:
  - conda-forge
  - pytorch
dependencies:
  # python version specified in Dockerfile
  - gxx
  - voms # x509 proxy system
  - ca-policy-lcg # WLCG trusted CAs
  - xrootd
  - htcondor
    # jupyter-related
  - jupyterlab
  - ipympl
  - dask_labextension
  - dask-jobqueue
  - dask-expr
  - bokeh
    # core scipy
    #- nomkl # no Intel math kernel library, reduces image size
  - numpy
  - scipy
  - pandas
    # compression
  - lz4
  - python-xxhash
  - zstandard
    # file formats
  - h5py
  - uproot<5
    # misc.
  - pytables
  - python-rapidjson
  - geventhttpclient
  - brotli
  - correctionlib
  - python-graphviz
    # scikit-hep
  - awkward<2
  - vector
  - hist
    # ML
  - xgboost
  - pytorch
  - torch-scatter
  - pip
  - coffea=0.7.22
  - pip:
    - fastjet==3.4.0.1 # LAST VERSION workking with awkward1
    - tritonclient[all]
    - tflite-runtime==2.14.0
    - onnxruntime
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - torch-geometric
    #- fsspec-xrootd
