name: base
channels:
  - conda-forge
  - pyg
  - pytorch
dependencies:
  # python version specified in Dockerfile
  - gxx
  - voms # x509 proxy system
  - ca-policy-lcg # WLCG trusted CAs
  - xrootd
  - htcondor=24.1.1 # pin HTCondor for LPC https://github.com/CoffeaTeam/lpcjobqueue/issues/38
  - curl
    # jupyter-related
  - jupyterlab
    ##- ipympl # no aarch64 support
  - dask_labextension
  - dask-gateway
  - dask-jobqueue
  - dask-expr
   # To be reverted: Dask needs to be pinned for now, do not use dask>=2024.12.0 with coffea, dask-awkward, or uproot
  - dask=2024.11.2
  - bokeh
  # Add workqueue
  - ndcctools
    # core scipy
    #- nomkl # no Intel math kernel library, reduces image size
  - numpy
  - scipy
  - pandas
    # compression
  - lz4
  - python-xxhash
  - zstandard
    # file formats
  - h5py
  - uproot<5
    # misc.
  - pytables
  - python-rapidjson
  - geventhttpclient
  - brotli
  - correctionlib
  - python-graphviz
    # scikit-hep
  - vector<1.5
  - hist
    # ML
  - xgboost
  - pytorch
  #- torch-scatter
  - pip
  - rucio-clients
    # pyg
    ##- pyg # no aarch64 support
    ##- pytorch-cluster # no aarch64 support
    ##- pytorch-sparse # no aarch64 support
    ##- pytorch-spline-conv # no aarch64 support
  - pip:
    - coffea==0.7.23
    - awkward==1.10.5
    - "setuptools<71"
    ##- fastjet==3.4.0.1 # LAST VERSION working with awkward1 # no aarch64 support
    - tritonclient[all]
    ##- tflite-runtime==2.14.0 # no aarch64 support
    - onnxruntime
    #- fsspec-xrootd