name: base
channels:
  - conda-forge
  - pyg
  - pytorch
dependencies:
  # python version specified in Dockerfile
  - gxx
  - voms # x509 proxy system
  - ca-policy-lcg # WLCG trusted CAs
  - xrootd
  - htcondor=24.1.1 # pin HTCondor for LPC https://github.com/CoffeaTeam/lpcjobqueue/issues/38
  - curl
    # jupyter-related
  - jupyterlab
  - ipympl
  - dask_labextension
  - dask-gateway
  - dask-jobqueue
  - dask-expr
   # To be reverted: Dask needs to be pinned for now, do not use dask>=2024.12.0 with coffea, dask-awkward, or uproot
  - dask<2025.4.0
  - bokeh
  # Add workqueue
  - ndcctools
    # core scipy
    #- nomkl # no Intel math kernel library, reduces image size
  - numpy
  - scipy
  - pandas
    # compression
  - lz4
  - python-xxhash
  - zstandard
    # file formats
  - h5py
  - uproot<5
    # misc.
  - pytables
  - python-rapidjson
  - geventhttpclient
  - brotli
  - correctionlib
  - python-graphviz
    # scikit-hep
  - vector<1.5
  - hist
    # ML
  - xgboost
  - pytorch
  - torch-scatter
  - pip
  - rucio-clients
    # pyg
  - pyg
  - pytorch-cluster
  - pytorch-sparse
  - pytorch-spline-conv
  - pip:
    - coffea==0.7.30
    - awkward==1.10.5
    - "setuptools<71"
    - fastjet==3.4.0.1 # LAST VERSION working with awkward1
    - tritonclient[all]
    - tflite-runtime==2.14.0
    - onnxruntime
    #- fsspec-xrootd
