name: base
channels:
  - conda-forge
  - pyg
  - pytorch
dependencies:
  # python version specified in Dockerfile
  - gxx
  - voms # x509 proxy system
  - ca-policy-lcg # WLCG trusted CAs
  - xrootd
  # we have issues with conflicting openssl version and htcondor 10.8.0 version is last one
  # which we able to resolve in this environment.yaml
  - htcondor
  - curl
    # jupyter-related
  - jupyterlab
  - ipympl
  - dask_labextension
  - dask-gateway
  - dask-jobqueue
  - bokeh
  # Add workqueue
  - ndcctools
    # core scipy
    #- nomkl # no Intel math kernel library, reduces image size
  - numpy
  - scipy
  - pandas
    # compression
  - lz4
  - python-xxhash
  - zstandard
    # file formats
  - h5py
  - uproot
    # misc.
  - pytables
  - python-rapidjson
  - geventhttpclient
  - brotli
  - correctionlib
  - python-graphviz
    # scikit-hep
  - awkward
  - vector
  - hist
    # ML
  #- xgboost
  - pytorch
  - torch-scatter
  - pip
  - coffea=2024.8.3
  - rucio-clients
    # pyg
  - pyg
  - pytorch-cluster
  - pytorch-sparse
  - pytorch-spline-conv
  - pip:
    - fastjet # to be added to conda-forge: https://github.com/scikit-hep/fastjet/issues/133
    - tritonclient[all]
    - tflite-runtime==2.14.0
    - onnxruntime
    - fsspec-xrootd
