name: base
channels:
  - conda-forge
  - pyg
  - pytorch
dependencies:
  # python version specified in Dockerfile
  #- gxx
  - voms # x509 proxy system
  - ca-policy-lcg # WLCG trusted CAs
  - xrootd
  - htcondor=24.1.1 # pin HTCondor for LPC https://github.com/CoffeaTeam/lpcjobqueue/issues/38
  - curl
    # jupyter-related
  - jupyterlab
  - ipympl
  - dask_labextension
  - dask-gateway
  - dask-jobqueue
  - dask<2025.4.0
  - dask-awkward
  - bokeh
  # Add workqueue
  - ndcctools
    # core scipy
    #- nomkl # no Intel math kernel library, reduces image size
  - numpy
  - scipy
  - pandas
    # compression
  - lz4
  - python-xxhash
  - zstandard
    # file formats
  - h5py
  - uproot>=5.6.2
    # misc.
  - pytables
  - python-rapidjson
  - geventhttpclient
  - brotli
  - correctionlib
  - python-graphviz
    # scikit-hep
  # FIXME: # disable microarches for awkward-cpp
  - awkward
  - vector
  - hist
    # ML
  - xgboost
  - pytorch
  - torch-scatter
  - pip
    # pyg
  - pyg
  - pytorch-cluster
  - pytorch-sparse
  - pytorch-spline-conv
  - rucio-clients
  - fastjet
  - coffea=2025.10.1
  - onnxruntime
  - fsspec-xrootd
  - pip:
    - tritonclient  #  more recent versions
