name: base
channels:
  - conda-forge
  - pyg
  - pytorch
dependencies:
  # python version specified in Dockerfile
  - gxx
  - voms # x509 proxy system
  - ca-policy-lcg # WLCG trusted CAs
  - xrootd
  # we have issues with conflicting openssl version and htcondor 10.8.0 version is last one
  # which we able to resolve in this environment.yaml
  - htcondor=24.1.1 # pin HTCondor for LPC https://github.com/CoffeaTeam/lpcjobqueue/issues/38
  - curl
    # jupyter-related
  - jupyterlab
  - ipympl
  - dask_labextension
  - dask-gateway
  - dask-jobqueue
  - dask<2025.4.0
  - dask-awkward
  - bokeh
  # Add workqueue
  - ndcctools
    # core scipy
    #- nomkl # no Intel math kernel library, reduces image size
  - numpy
  - scipy
  - pandas
    # compression
  - lz4
  - python-xxhash
  - zstandard
    # file formats
  - h5py
  - uproot>=5.6.2
    # misc.
  - pytables
  - python-rapidjson
  - geventhttpclient
  - brotli
  - correctionlib
  - python-graphviz
    # scikit-hep
  # FIXME: # disable microarches for awkward-cpp
  - awkward
  - vector
  - hist
    # ML
  #- xgboost
  - torch-scatter
  - pip
    # pyg
  - pyg
  - pytorch-cluster
  - pytorch-sparse
  - pytorch-spline-conv
  #- coffea=2025.7.3
  - rucio-clients
  - fastjet
  - coffea=2025.7.3
  - pip:
    - tritonclient[all]
    - ai-edge-litert-nightly # ai-edge-litert as replacement of tflite is still not available for python
    - onnxruntime
    - fsspec-xrootd
    - torch
